apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
spec:
  type: NodePort
  ports:
  - name: query-state
    port: 6125
    targetPort: 6125
  selector:
    app: flink
    component: taskmanager